Bunmp Rust version to 1.88.0
When compiling `polakdot-sdk`:

error: rustc 1.87.0 is not supported by the following packages:
  revm-bytecode@6.2.2 requires rustc 1.88.0
  revm-database@7.0.5 requires rustc 1.88.0
  revm-database-interface@7.0.5 requires rustc 1.88.0
  revm-primitives@20.2.1 requires rustc 1.88.0
  revm-state@7.0.5 requires rustc 1.88.0